version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - QRaimbault
      - Araknyfe
    assignees:
      - QRaimbault
      - Araknyfe
    labels:
      - chore
      - dependencies
    commit-message:
      prefix: "Upgrade: "
